name: "last-nest-migration update"
on:
  schedule:
  - cron: "0 2 */14 * *"

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time 
      - name: Set new Timestamp
        run: "echo ${{ "{{ steps.current-time.outputs.time" }}}} > last-nest-migration-ts"