name: "last-nest-migration update"
on:
  schedule:
  - cron: "0 * * * *"
jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
    - name: Timestamp
      id: create_timestamp
      run: echo TS=$(date +%s) >> $GITHUB_ENV
    - name: Set new Timestamp
      run: "echo ${{ env.TS }} > last-nest-migration"
    - name: write new timestampfile
      uses: "DamianReeves/write-file-action@master"
      with:
        path: nests/last-regular-migration
        write-mode: overwrite
        contents: ${{ env.TS }}
